### ISSUE TITLE
Is fluent-plugin-newsyslog ready for use?

### ISSUE THREAD

**Issue by jesper** [athenahealth/fluent-plugin-newsyslog#1]
I can't seem to install it via gem - and can't be found on rubygems.org either.

https://rubygems.org/search?utf8=%E2%9C%93&query=fluent-plugin-newsyslog

**Comment by scheuk** [comment]
Jesper, 
this is my first stab at a gem or fluent plugin.
I'll get a gem released with this version of the code today.

**Comment by scheuk** [comment]
Jesper I just released my plugin as a gem,
Feel free to give it a try and let me know if there is any problems.
